apiVersion: apps/v1
kind: Deployment
metadata:   
    labels:
        io.kompose.service: bunny
    name: bunny
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        image: postgres:9.4
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /healthchecks/postgres.sh
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data-igut25
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -c
        - true && if [ -d "/mnt/bns/volume-0/lost+found" ];then rm -rf /mnt/bns/volume-0/lost+found;
          fi && chmod 777 /mnt/bns/volume-0
        command:
        - /bin/sh
        image: busybox:1.35.0@sha256:506593a4eb16efb7160a37d716ed9ca7b20a337d400207f29c504fcb64982bcc
        imagePullPolicy: IfNotPresent
        name: bns-volume-permissions
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/bns/volume-0
          name: db-data-igut25
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      volumes:
      - name: db-data-igut25
        persistentVolumeClaim:
          claimName: db-data-igut25