apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/part-of: env-igut25
  name: db-data-igut25
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: bns-disk-sc
  volumeMode: Filesystem
  volumeName: pvc-05dceb94-6bc7-433f-9c37-922300ebb94b
