apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bunny
  name: bunny
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    io.kompose.service: bunny
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}