apiVersion: apps/v1
kind: Deployment
metadata:   
    labels:
        io.kompose.service: bunny
    name: bunny
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - env:
        - name: BNS_DEPLOY_TIMESTAMP
          value: "2023-01-01T20:53:20+00:00"
        envFrom:
        - configMapRef:
            name: project-variables
        - configMapRef:
            name: environment-variables
        - configMapRef:
            name: bns-builtin-env-vars
        - configMapRef:
            name: bns-builtin-redis-env-vars
        image: redis:5.0-alpine3.10
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /healthchecks/redis.sh
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP        
      imagePullSecrets:
      - name: bns-reg-cred-igut25-0
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64