apiVersion: apps/v1
kind: Deployment
metadata:   
    labels:
        io.kompose.service: worker
    name: worker
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 0
    selector:
        matchLabels:
            io.kompose.service: worker
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                io.kompose.service: worker
        spec:
            containers:
                -
                    image: {{ .Values.images.worker}}
                    imagePullPolicy: IfNotPresent
                    name: worker
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            tolerations:
                -
                    effect: NoSchedule
                    key: kubernetes.io/arch
                    operator: Equal
                    value: amd64